### ISSUE TITLE
Failed to load Slack channels

### ISSUE THREAD

**Issue by peternagelsa** [nextcloud/integration_slack#17]
Running Nextcloud 29.0.2 and Slack App version 1.1.0. Connection is established between Nextcloud and Slack Workspace, but when sharing a file, it does not load the channel(s) generating 'failed to load slack channels' 

Is this a bug or a wrong configuration?

**Comment by erikauer** [comment]
Hi @peternagelsa,

I experienced the same issue. I think it is related to the channels and groups are requested from slack. There are channel names as well us group names. At groups names it seems that there are null values:

![bug](https://github.com/user-attachments/assets/e2154742-e6b7-4bfd-8cda-87010926535a)

I guess this lines need to be fixed here: 

https://github.com/nextcloud/integration_slack/blob/10c77241090fdbd404c4decc974c324a9faab8e4/src/components/SendFilesModal.vue#L360

because in localeCompare there is no check for null values in b.name:

		updateChannels() {
			const url = generateUrl('apps/integration_slack/channels')
			axios.get(url).then((response) => {
				this.channels = response.data ?? []
				this.channels.sort((a, b) => a.name.localeCompare(b.name))
				if (this.channels.length > 0) {
					this.selectedChannel = this.channels[0]
				}
			}).catch((error) => {
				showError(t('integration_slack', 'Failed to load Slack channels'))
				console.error(error)
				this.channels = []
			})

**Comment by kyteinsky** [comment]
Hi @erikauer, thanks for the analysis. Would you mind doing a pull request?

@peternagelsa, would you mind posting the console logs (Ctrl+Shift+i) to verify if it is the same issue?
