### ISSUE TITLE
[enh] send to channel - channels must be sorted alphabetically

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/integration_slack#6]
currently the channel list is "random" (probably internal ID is used)

**Comment by kyteinsky** [comment]
the channels/groups are sorted by the `updated` parameter that is supplied by the Slack API but it seems it is not the last message update time but the update time of the channel/group settings. I'll look into it.  
I have marked this as an enhancement because that sort (update-based) is not working and this is a new addition. If Slack does not provide that info, we'll go with this one.
